
name: output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Angular CLI
        run: |
          npm install
          npm install -g @angular/cli 
      - name: Run Angular lint
        continue-on-error: true
        run: |
           ng add @angular-eslint/schematics --skip-confirmation
           ng lint > log.txt 2>&1; echo $?
           cat $GITHUB_WORKSPACE/log.txt | grep "linting" >> $GITHUB_WORKSPACE/errors.txt
      - name: Generate HTML Summary
        if: always()
        run: |
          echo "<html><body><pre>" > $GITHUB_WORKSPACE/summary.html
          cat $GITHUB_WORKSPACE/errors.txt >> $GITHUB_WORKSPACE/summary.html
          echo "</pre></body></html>" >> $GITHUB_WORKSPACE/summary.html
          cat $GITHUB_WORKSPACE/summary.html >> $GITHUB_STEP_SUMMARY
           
      - name: test
        run: |
          ng test --watch=false --browsers=ChromeHeadless 
